import React from "react";

const App = (props) => {
  const { notes } = props

  return(
    <div>
      <h1>Notes</h1>
      <ul>
        {/* enerating React elements from the array objects using the map function */}
        {notes.map(note =>  
          // We are encouraged by React to include a key attribute
          // used to determine how to update the view generated by a component when the component is re-rendered
          <li key={note.id}>
            {note.content}
          </li>
        )}
      </ul>
    </div>
  )
}

export default App
