import React from "react";

// Common practice is to declare each component in its own file as an ES6-module.
// omponents are usually placed in a directory called components, - we name the file after the component
const Note = ({note}) => {
  return (
    <li>{note.content}</li>
  )
}

const App = ({notes}) => {
  return(
    <div>
      <h1>Notes</h1>
      <ul>
        {/* enerating React elements from the array objects using the map function */}
        {notes.map(note =>  
          // We are encouraged by React to include a key attribute
          // used to determine how to update the view generated by a component when the component is re-rendered

          // we could also add a second param to map i, to use array index as our key but not recommended

          // now we define key for the Note components, and not for the li tags like before.
          <Note key={note.id} note={note} />
        )}
      </ul>
    </div>
  )
}

export default App
